### PR TITLE
Helix Pages support code

### PR DESCRIPTION
**Pull request by koraa**
Will be merged thursday around noon

### CODE REVIEW

**Comment by trieloff** [comment]
Looks good, but I'd prefer this to simply introduce the right extension mechanisms so that it works with #87, i.e. have callbacks in `hlx_owner`, etc.

**Comment by koraa** [comment]
I've looked at the extension points; right now they are not powerful enough; I suggest we use the new code for helix pages support as a basis to design the extension support around. This way, we can get rid of special cases one by one.

**Comment by kptdobe** [comment]
-1
Add project specific code inside the product is not nice, especially now that we are about to have an extension point mechanism.

> I suggest we use the new code for helix pages support as a basis to design the extension support around.

That's exactly how I proceed. I am adding the only extension point (and all the machinery around to support it) I need to cover "my" current needs. Once we move forward, we can add more. Feel free to open an issue for the extension point(s) you would need.

**Comment by koraa** [comment]
It's not really project specific as helix pages will replace the helix-cli way of deploying any helix pages; since helix pages is a very core aspect of helix, it should not be put into an extra repo IMO.
I'd be happy to utilize your extension functions @kptdobe, however they are not up to the tasks; I did have a look at them before writing this PR.

@kptdobe Could you please demonstrate how the functionality of helix pages could be achieved with your extension points? If it's not possible I would like to go ahead with this as helix pages is high priority.

**Comment by rofe** [comment]
> helix pages will replace the helix-cli way of deploying any helix pages

When was that decision taken? Is it persisted somewhere? I thought that subject still needs to be discussed, hence the breakout session at the next hackathon...

**Comment by kptdobe** [comment]
Let discuss about this PR next week at the hackathon.

**Comment by kptdobe** [comment]
> helix pages will replace the helix-cli way of deploying any helix pages

@koraa it is not on your roadmap, @davidnuescheler removed this confusing sentence:
https://github.com/adobe/project-helix/commit/70e5ecfb18967084f8897b57837c887e03018b64#diff-334f2a839b7a966b08f306945f7a76fc

**Comment by kptdobe** [comment]
> [extension functions] however they are not up to the tasks

In the current helix-pages repo, I created the required extensions to use the subdomain to compute the owner / repo / ref based on the pattern:
https://github.com/adobe/helix-pages/pull/12/files

You can inspire from that and if an extension point is missing, you can make a PR to add it. See:
https://github.com/adobe/helix-publish/pull/93

**Pull request closed without merging**
