### PR TITLE
feat(helix.vcl): enable caching of blocked requests

### LINKED ISSUE #600: Return 404 instead of 403 for blocked requests
**Is your feature request related to a problem? Please describe.**
Requests with url paths matching the "bad request" regex currently return status `403 - Forbidden`. This poses a problem for outer CDNs as status 403 is by default [not cached by Fastly](https://docs.fastly.com/en/guides/http-status-codes-cached-by-default). 

**Describe the solution you'd like**
Such requests should rather return 404 which is by default cached by CDNs.

**Additional context**

### PR DESCRIPTION
**Pull request by stefan-guggisberg**
fix #600

Please ensure your pull request adheres to the following guidelines:
- [ ] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues

Thanks for contributing!

### CODE REVIEW

**Review by tripodsan — APPROVED** [review]

**Review by trieloff — CHANGES_REQUESTED** [review]
That will make it hard for us to assess the proportion of malicious requests.

You could create a new synthetic response path that looks like a 404, but adds a `req.http.X-Status = 403;` and then we'd adjust the log schema to use `req.http.X-Status` for `cdn.status` with higher prio than `resp.status`.

**Comment by stefan-guggisberg** [comment]
hmm, sounds overly complicated. 

BTW: there are still quite a lot of baddies which aren't caught by the regex. They already return 404.

**Comment by davidnuescheler** [comment]
after just reviewing the logs the of a real life 24h, i can definitely support that the "malicious requests" are currently returning a mix 403 and 404's alike and i really don't see any value in reporting an arbitrary portion of those as 403, i find it actually quite annoying when looking through the logs that i have to query both to get a complete picture.

the bigger problem is that we have false positives (or negatives depending how you look at it) with the current regex, which surface as a 403 for legitimate URLs, which is where a 404 would be very hard to diagnose for the user. 
however, the main problem is the complexity of the regex, so we should really fix that.

**Comment by tripodsan** [comment]
@stefan-guggisberg @trieloff @davidnuescheler can we close this `won't fix` ?

**Pull request closed without merging**
