### PR TITLE
fix(content): allow cors headers for lnk request type

### LINKED ISSUE #830: Set CORS headers for known Helix origins
In order to allow cross-origin requests between Helix domains (e.g. sending a `HLXPURGE` or `POST` request to `https://foo--bar.hlx.live` from `https://foo--bar.hlx.live` (see also https://github.com/adobe/helix-pages/issues/854), we would need to set the `Access-Control-Allow-Origin` and `Access-Control-Allow-Methods` headers. 

Ideally we would set these on the inner CDN and let them bubble up to the outer CDN(s). 

Pseudo VCL: 
```
if (req.http.Origin` ~ "*.hlx.page" || req.http.Origin ~ "*.hlx.live") {
  set obj.http.Access-Control-Allow-Origin = req.http.Origin;
  set obj.http.Access-Control-Allow-Methods = "OPTIONS, POST, HLXPURGE";
}
```

(The `Access-Control-Allow-Methods` should ideally prevent sending the `Access-Control-Allow-Origin` header in a response that may be cached downstream, so we could avoid having to `Vary` on `Origin`.)

See also https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

### PR DESCRIPTION
**Pull request by trieloff**
Alternative to #869 as suggested by @tripodsan – @rofe please test. Fixes #830

### CODE REVIEW

**Comment by rofe** [comment]
> @rofe please test

Works 👍

**Review by rofe — APPROVED** [review]

**Comment by trieloff** [comment]
Ok, so now we just need to get it through the integration test from hell.

**Comment by rofe** [comment]
I'd also appreciate a quick look from @tripodsan.

**Review by tripodsan — APPROVED** [review]

**Pull request merged**
