### PR TITLE
feat: re-enable http/2

### PR DESCRIPTION
**Pull request by stefan-guggisberg**
Please ensure your pull request adheres to the following guidelines:
- [ ] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues

Thanks for contributing!

### CODE REVIEW

**Comment by trieloff** [comment]
I really think http isn't working in runtime for fastly, but we can leave this open until the tests pass.

**Comment by stefan-guggisberg** [comment]
> I really think http isn't working in runtime for fastly, but we can leave this open until the tests pass.

Ok. I would just like to know the exact reason why it's not working.

**Comment by stefan-guggisberg** [comment]
Might be a problem in the Epsagon Http/2 support. Do. you know how we can disable Epsagon for this test?

**Comment by trieloff** [comment]
Only by deploying to a private namespace, epsagon is baked in by hedy.

**Comment by tripodsan** [comment]
> Only by deploying to a private namespace, epsagon is baked in by hedy.

i was working on a way to configure this:
https://github.com/adobe/helix-deploy/pull/70

**Comment by stefan-guggisberg** [comment]
> > Only by deploying to a private namespace, epsagon is baked in by hedy.
> 
> i was working on a way to configure this:
> [adobe/helix-deploy#70](https://github.com/adobe/helix-deploy/pull/70)

That would be great.

**Comment by tripodsan** [comment]
@stefan-guggisberg I try to debug a test with helix-fetch, but it doesn't produce any debug output:

```
$ export DEBUG=helix-fetch*
$ echo $DEBUG
helix-fetch*
$ ./node_modules/.bin/mocha test/check-pkg.test.js


  test check_pkgs
Status check for strain adhoc2 failed when invoking https://adobeioruntime.net/api/v1/web/mrosier/c4763cd3420bf015454e2e1f2ce2ecd1dd1ca942/html/_status_check/healthcheck.json: 500
    1) checkPkgs works successfully
```

**Review by trieloff — APPROVED** [review]
I like the `discard` cleanup, but think that HTTP/2 will break again. Let's see.

**Comment by stefan-guggisberg** [comment]
> @stefan-guggisberg I try to debug a test with helix-fetch, but it doesn't produce any debug output:

weird, it works for me:
```
export DEBUG=helix-fetch*
./node_modules/.bin/mocha test/check-pkg.test.js


  test check_pkgs
  helix-fetch:core established TLS connection: #1 (adobeioruntime.net) +0ms
  helix-fetch:core adobeioruntime.net -> http/1.1 +1ms
  helix-fetch:h1 GET https://adobeioruntime.net/api/v1/web/mrosier/d90a42b1babf33d430450e05cbd3dc1edc6b7135/html/_status_check/healthcheck.json +0ms
  helix-fetch:h1 discarding redundant socket used for ALPN: #1 adobeioruntime.net +11ms
  helix-fetch:core adobeioruntime.net -> http/1.1 +15ms
  helix-fetch:h1 GET https://adobeioruntime.net/api/v1/web/mrosier/9d723ce487448cc132cd240a484b65772b201241/html/_status_check/healthcheck.json +4ms
  helix-fetch:h1 discarding redundant socket used for ALPN: #1 adobeioruntime.net +2ms
  helix-fetch:core established TLS connection: #2 (deploy-test.anywhere.run) +3ms
  helix-fetch:core deploy-test.anywhere.run -> http/1.1 +0ms
  helix-fetch:h1 GET https://deploy-test.anywhere.run/pages_4.15.4/html/_status_check/healthcheck.json +1ms
  helix-fetch:h1 discarding redundant socket used for ALPN: #2 deploy-test.anywhere.run +1ms
  helix-fetch:core adobeioruntime.net -> http/1.1 +2ms
  helix-fetch:h1 GET https://adobeioruntime.net/api/v1/web/mrosier/c4763cd3420bf015454e2e1f2ce2ecd1dd1ca942/html/_status_check/healthcheck.json +1ms
  helix-fetch:h1 discarding redundant socket used for ALPN: #1 adobeioruntime.net +2ms
    ✓ checkPkgs works successfully (267ms)
  helix-fetch:core adobeioruntime.net -> http/1.1 +97ms
  helix-fetch:h1 GET https://adobeioruntime.net/api/v1/web/fake/d90a42b1babf33d430450e05cbd3dc1edc6b7135dafa/html/_status_check/healthcheck.json +95ms
  helix-fetch:core adobeioruntime.net -> http/1.1 +1ms
  helix-fetch:h1 GET https://adobeioruntime.net/api/v1/web/fake/9d723ce487448cc132cd240a484b65772b201241/html/_status_check/healthcheck.json +1ms
  helix-fetch:core adobeioruntime.net -> http/1.1 +1ms
  helix-fetch:h1 GET https://adobeioruntime.net/api/v1/web/fake/c4763cd3420bf015454e2e1f2ce2ecd1dd1ca942/html/_status_check/healthcheck.json +1ms
Status check for strain adhoc1 failed when invoking https://adobeioruntime.net/api/v1/web/fake/9d723ce487448cc132cd240a484b65772b201241/html/_status_check/healthcheck.json: 404 Not Found
    ✓ checkPkgs fails if one check fails (98ms)


  2 passing (376ms)
```

**Comment by stefan-guggisberg** [comment]
tests succeeded! :)

**Comment by stefan-guggisberg** [comment]
It's really weird. I can't reproduce the failing smoke test locally. Publishing (using h2) always succeeds:
```
  Integration Test
[INFO] helix-publish: parsing body 
[INFO] body text: {"service":"54nWWFJicKgbdVHou26Y6a","token":"QI_ltvu7WfvBYUrOgpSV9cfttF4iwjyR","version":316,"configuration":{"version":1,"preflight":"https://adobeioruntime.net/example","strains":{"adhoc":{"code":{"host":"github.com","hostname":"github.com","owner":"adobe","path":"","port":"","protocol":"https","ref":"master","repo":"project-helix.io"},"condition":{"preflight.x-version>":1},"content":{"host":"github.com","hostname":"github.com","owner":"adobe","path":"","port":"","protocol":"https","ref":"master","repo":"project-helix.io"},"directoryIndex":"index.html","name":"adhoc","package":"75f29aa936bfc2b84bde5ac0ee4afbf824b1391e-dirty","perf":{"connection":"","device":"","location":"London","onload":1000},"static":{"allow":[],"deny":[],"host":"github.com","hostname":"github.com","magic":false,"owner":"adobe","path":"/htdocs","port":"","protocol":"https","ref":"master","repo":"project-helix.io"},"sticky":true,"urls":[]},"default":{"code":{"protocol":"ssh","host":"github.com","port":"","hostname":"github.com","owner":"adobe","repo":"helix-cli","ref":"","path":""},"content":{"protocol":"ssh","host":"github.com","port":"","hostname":"github.com","owner":"adobe","repo":"helix-cli","ref":"","path":""},"static":{"magic":false,"allow":[],"deny":[],"protocol":"ssh","host":"github.com","port":"","hostname":"github.com","owner":"adobe","repo":"helix-cli","ref":"","path":"/htdocs"},"directoryIndex":"index.html","package":"mrosier/9d723ce487448cc132cd240a484b65772b201241","sticky":false,"condition":{"url":"https://www.project-helix.io/cli"},"perf":{"device":"","location":"","connection":""},"urls":["https://www.project-helix.io/cli"],"redirects":[{"from":"(.*)\\.php","to":"$1.html"}]}}},"indexconfig":{"indices":{"blog-posts":{"fetch":"https://${repo}-${owner}.project-helix.page/${path}","properties":{"author":{"faceted":true,"select":"main > div:nth-of-type(3) > p:nth-of-type(1)","value":"${match('by (.*)')}\n"},"date":{"select":"main > div:nth-of-type(3) > p:nth-of-type(2)","value":"${parseTimestamp('[POSTED ON] MM-DD-YYYY')}\n"},"hero":{"select":"main > div > img:first-of-type","value":"${attribute('src')}\n"},"title":{"select":"h1:first-of-type","value":"${textContent()}\n"},"topics":{"faceted":true,"select":"main > div:last-of-type > p:first-of-type","values":"${match('(Topics: )? ([^,]+)')}\n"}},"queries":{"all":{"cache":600,"hitsPerPage":25,"query":"*","parameters":[],"select":"*"},"by-author":{"cache":300,"filters":"author:${author}\n","hitsPerPage":25,"parameters":["author"],"query":"*","select":"*"}},"source":"html"}},"version":1},"algoliaappid":"A8PL9E4TZT","epsagontoken":"478bd573-911f-466c-9898-3de2649d9eb9"}
[INFO] running publishing tasks…
  helix-fetch:core established TLS connection: #1 (api.fastly.com) +0ms
  helix-fetch:core api.fastly.com -> h2 +1ms
  helix-fetch:h2 reusing socket #1 (api.fastly.com) +0ms
  helix-fetch:h2 POST api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/vcl +1ms
  helix-fetch:h2 session https://api.fastly.com established +2ms
  helix-fetch:h2 caching session https://api.fastly.com +0ms
  helix-fetch:h2 session https://api.fastly.com remoteSettings: {"headerTableSize":4096,"enablePush":true,"initialWindowSize":65535,"maxFrameSize":16384,"maxConcurrentStreams":100,"maxHeaderListSize":4294967295,"maxHeaderSize":4294967295,"enableConnectProtocol":false} +19ms
  helix-fetch:h2 session https://api.fastly.com localSettings: {"headerTableSize":4096,"enablePush":true,"initialWindowSize":65535,"maxFrameSize":16384,"maxConcurrentStreams":4294967295,"maxHeaderListSize":4294967295,"maxHeaderSize":4294967295,"enableConnectProtocol":false} +0ms
  helix-fetch:core api.fastly.com -> h2 +268ms
  helix-fetch:h2 PUT api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/vcl/dynamic.vcl +245ms
  helix-fetch:core api.fastly.com -> h2 +310ms
  helix-fetch:h2 POST api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/vcl +310ms
  helix-fetch:core api.fastly.com -> h2 +182ms
  helix-fetch:h2 PUT api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/vcl/extensions.vcl +183ms
  helix-fetch:core api.fastly.com -> h2 +272ms
  helix-fetch:h2 POST api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/vcl +271ms
  helix-fetch:core api.fastly.com -> h2 +1ms
  helix-fetch:h2 POST api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/vcl +1ms
  helix-fetch:core api.fastly.com -> h2 +0ms
  helix-fetch:h2 POST api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/vcl +0ms
  helix-fetch:core api.fastly.com -> h2 +313ms
  helix-fetch:h2 PUT api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/vcl/params.vcl +313ms
  helix-fetch:core api.fastly.com -> h2 +1ms
  helix-fetch:h2 PUT api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/vcl/preflight.vcl +1ms
  helix-fetch:core api.fastly.com -> h2 +1ms
  helix-fetch:h2 PUT api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/vcl/strains.vcl +1ms
  helix-fetch:core api.fastly.com -> h2 +323ms
  helix-fetch:h2 POST api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/vcl +323ms
  helix-fetch:core api.fastly.com -> h2 +209ms
  helix-fetch:h2 PUT api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/vcl/queries.vcl +209ms
  helix-fetch:core api.fastly.com -> h2 +381ms
  helix-fetch:h2 POST api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/backend +381ms
  helix-fetch:core api.fastly.com -> h2 +0ms
  helix-fetch:h2 POST api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/backend +1ms
  helix-fetch:core api.fastly.com -> h2 +1ms
  helix-fetch:h2 POST api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/backend +0ms
  helix-fetch:core api.fastly.com -> h2 +0ms
  helix-fetch:h2 POST api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/backend +0ms
  helix-fetch:core api.fastly.com -> h2 +0ms
  helix-fetch:h2 POST api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/backend +0ms
  helix-fetch:core api.fastly.com -> h2 +0ms
  helix-fetch:h2 POST api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/backend +0ms
  helix-fetch:core api.fastly.com -> h2 +0ms
  helix-fetch:h2 POST api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/vcl +0ms
  helix-fetch:core api.fastly.com -> h2 +1ms
  helix-fetch:h2 POST api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/vcl +1ms
  helix-fetch:core api.fastly.com -> h2 +2ms
  helix-fetch:h2 GET api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/condition +2ms
  helix-fetch:core api.fastly.com -> h2 +0ms
  helix-fetch:h2 GET api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/dictionary/secrets +0ms
  helix-fetch:core api.fastly.com -> h2 +0ms
  helix-fetch:h2 GET api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/dictionary/strain_action_roots +0ms
  helix-fetch:core api.fastly.com -> h2 +0ms
  helix-fetch:h2 GET api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/dictionary/strain_owners +0ms
  helix-fetch:core api.fastly.com -> h2 +0ms
  helix-fetch:h2 GET api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/dictionary/strain_refs +0ms
  helix-fetch:core api.fastly.com -> h2 +6ms
  helix-fetch:h2 GET api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/dictionary/strain_repos +6ms
  helix-fetch:core api.fastly.com -> h2 +0ms
  helix-fetch:h2 GET api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/dictionary/strain_root_paths +0ms
  helix-fetch:core api.fastly.com -> h2 +0ms
  helix-fetch:h2 GET api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/dictionary/strain_github_static_repos +0ms
  helix-fetch:core api.fastly.com -> h2 +0ms
  helix-fetch:h2 GET api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/dictionary/strain_github_static_owners +0ms
  helix-fetch:core api.fastly.com -> h2 +0ms
  helix-fetch:h2 GET api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/dictionary/strain_github_static_refs +1ms
  helix-fetch:core api.fastly.com -> h2 +1ms
  helix-fetch:h2 GET api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/dictionary/strain_github_static_root +0ms
  helix-fetch:core api.fastly.com -> h2 +0ms
  helix-fetch:h2 GET api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/dictionary/strain_index_files +0ms
  helix-fetch:core api.fastly.com -> h2 +0ms
  helix-fetch:h2 GET api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/dictionary/strain_allow +0ms
  helix-fetch:core api.fastly.com -> h2 +0ms
  helix-fetch:h2 GET api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/dictionary/strain_deny +0ms
  helix-fetch:core api.fastly.com -> h2 +0ms
  helix-fetch:h2 GET api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/dictionary/strain_version_lock +0ms
  helix-fetch:core api.fastly.com -> h2 +1ms
  helix-fetch:h2 GET api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/logging/https/helix-epsagon +1ms
  helix-fetch:core api.fastly.com -> h2 +228ms
  helix-fetch:h2 PUT api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/backend/AdobeFonts +228ms
  helix-fetch:core api.fastly.com -> h2 +1ms
  helix-fetch:h2 PUT api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/backend/Algolia +1ms
  helix-fetch:core api.fastly.com -> h2 +1ms
  helix-fetch:h2 PUT api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/logging/https/helix-epsagon +1ms
  helix-fetch:core api.fastly.com -> h2 +1ms
  helix-fetch:h2 PUT api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/vcl/reset.vcl +1ms
  helix-fetch:core api.fastly.com -> h2 +0ms
  helix-fetch:h2 PUT api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/backend/GitHub +0ms
  helix-fetch:core api.fastly.com -> h2 +5ms
  helix-fetch:h2 GET api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/header +5ms
  helix-fetch:core api.fastly.com -> h2 +7ms
  helix-fetch:h2 PUT api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/backend/UniversalRuntime +7ms
  helix-fetch:core api.fastly.com -> h2 +11ms
  helix-fetch:h2 PATCH api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/dictionary/6tmAIs0aCfNXF6zsmtNScQ/items +11ms
  helix-fetch:core api.fastly.com -> h2 +0ms
  helix-fetch:h2 PATCH api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/dictionary/6tlvGa6erOOoBYRvJT7hS9/items +0ms
  helix-fetch:core api.fastly.com -> h2 +2ms
  helix-fetch:h2 PUT api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/backend/AzureBlobs +2ms
  helix-fetch:core api.fastly.com -> h2 +294ms
  helix-fetch:h2 PUT api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/backend/AdobeRuntime +294ms
  helix-fetch:core api.fastly.com -> h2 +199ms
  helix-fetch:h2 PUT api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/vcl/helix.vcl +199ms
  helix-fetch:core api.fastly.com -> h2 +1s
  helix-fetch:h2 PATCH api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/dictionary/6tS8lvtRx0hWi7PATiYTlg/items +1s
  helix-fetch:core api.fastly.com -> h2 +3s
  helix-fetch:h2 PATCH api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/dictionary/6tmoyiJsES3E5YlwmjF8ls/items +3s
  helix-fetch:core api.fastly.com -> h2 +1s
  helix-fetch:h2 PATCH api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/dictionary/6tmANh9iLMvWGSoWMt2xIe/items +1s
  helix-fetch:core api.fastly.com -> h2 +1s
  helix-fetch:h2 PATCH api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/dictionary/3ovyFLrfhurRT4VXkjCjaq/items +1s
  helix-fetch:core api.fastly.com -> h2 +1s
  helix-fetch:h2 PATCH api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/dictionary/5JPgAr0Srq1SKY0EnxtrOK/items +1s
  helix-fetch:core api.fastly.com -> h2 +1s
  helix-fetch:h2 PATCH api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/dictionary/5JPU8atUUXBuUOXhK5Zctk/items +1s
  helix-fetch:core api.fastly.com -> h2 +1s
  helix-fetch:h2 PATCH api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/dictionary/5Jdxbb1yW7RnHsZU4r5mF6/items +1s
  helix-fetch:core api.fastly.com -> h2 +1s
  helix-fetch:h2 PATCH api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/dictionary/1C7mznzU9PHL2isc4Qah6L/items +1s
  helix-fetch:core api.fastly.com -> h2 +823ms
  helix-fetch:h2 PATCH api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/dictionary/3Im6QICsW4nWwmJfXOnkOG/items +823ms
  helix-fetch:core api.fastly.com -> h2 +1s
  helix-fetch:h2 PATCH api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/dictionary/0Z4tRqFgpgkkMuicA4X32T/items +1s
  helix-fetch:core api.fastly.com -> h2 +897ms
  helix-fetch:h2 PATCH api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/dictionary/0WXB6n1Uk6fR1CQ1cdPmPo/items +897ms
  helix-fetch:core api.fastly.com -> h2 +3s
  helix-fetch:h2 PUT api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/vcl/helix.vcl/main +3s
[INFO] completed 11 tasks.
  helix-fetch:core resetting context +0ms
  helix-fetch:h2 resetContext: destroying session (socket #1, api.fastly.com) +551ms
https://api.fastly.com /service/54nWWFJicKgbdVHou26Y6a/version/316/validate
  helix-fetch:h2 session https://api.fastly.com closed +15ms
  helix-fetch:h2 discarding cached session https://api.fastly.com +0ms
    ✓ Test publish function locally (24290ms)
```

Interestingly the smoke tests seem to fail always at the same step:
```
error: Remote publish service failed Error: 500 - "{"status":"error","message":"AbortError: Aborted put request to /service/**********************/version/514/vcl/helix.vcl/main after 0 retries and 15005 ms: The operation was aborted."
```

That's the final step in the publish tasks sequence:

`PUT api.fastly.com/service/54nWWFJicKgbdVHou26Y6a/version/316/vcl/helix.vcl/main +3s`

**Comment by tripodsan** [comment]
included in https://github.com/adobe/helix-publish/pull/820

**Pull request closed without merging**
