### PR TITLE
fix(vcl): allow wider blob hash

### PR DESCRIPTION
**Pull request by tripodsan**
for the new blob hashes we need to allow longer sequences.

### CODE REVIEW

**Review by trieloff — CHANGES_REQUESTED** [review]
There is at least one other occurrence, search for `if (req.url.path ~ "^/hlx_(([0-9a-f]){40}).([0-9a-z]+)$" || req.url.path ~ "/media_(([0-9a-f]){40}).([0-9a-z]+)$") {`

**Comment by kptdobe** [comment]
This is a pretty serious change, are we sure about the regex ?

**Comment by tripodsan** [comment]
> This is a pretty serious change, are we sure about the regex ?

I'm sure about the regexp, but I'm not sure if we don't have other locations we look for 40 characters.
but we'll find out quickly. this PR is probably not a problem.

**Review by trieloff — APPROVED** [review]

**Pull request merged**
