### PR TITLE
fix(backends): increase Fastly timeouts

### PR DESCRIPTION
**Pull request by trieloff**
as suggested by @tysonnorris in https://adobe.slack.com/archives/C68UJPDM5/p1596033493473200?thread_ts=1595840508.428700&cid=C68UJPDM5

This could reduce the amount of 503s we are seeing.

### CODE REVIEW

**Comment by stefan-guggisberg** [comment]
60s connect timeout seems excessive. I'd start with 5s. If we're still seeing connect timeouts then something's truly broken.

**Comment by trieloff** [comment]
@stefan-guggisberg I've updated to 5 seconds.

**Comment by stefan-guggisberg** [comment]
@trieloff You've also decreased the `between-bytes-timeout` to 5s (used to be 10s, the default).  I would leave that at the default value.

**Comment by trieloff** [comment]
Done

**Pull request merged**
